create database coffee_db;

create table types
(
    id   int generated by default as identity primary key,
    name varchar(50) unique not null
);

create table assortment
(
    id       int generated by default as identity primary key,
    ru_name  varchar(50) unique not null,
    eng_name varchar(50) unique not null,
    price    decimal,
    type_id  int references types (id)
);

create table staff_positions
(
    id   int generated by default as identity primary key,
    name varchar(30) not null unique
);

create table staff
(
    id          int generated by default as identity primary key,
    firstname   varchar(30),
    lastname    varchar(30),
    tel         varchar(20),
    address     varchar(150),
    position_id int references staff_positions
);

create table clients
(
    id        int generated by default as identity primary key,
    firstname varchar(30),
    lastname  varchar(30),
    birthdate date,
    tel       varchar(20),
    address   varchar(150),
    discount  int
);

insert into staff_positions (name)
values ('Бариста'),
       ('Официант'),
       ('Кондитер');

insert into assortment (ru_name, eng_name, price, type_id)
VALUES ('nameE', 'nameR', 100.50,
           (select id from types where name='DRINK')
       );
